# Generated by Django 3.1 on 2020-08-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('email_host', models.TextField()),
                ('email_user', models.TextField()),
                ('email_port', models.TextField()),
                ('email_password', models.TextField()),
                ('email_from', models.TextField()),
                ('default_email_from', models.TextField()),
            ],
            options={
                'db_table': 'email_settings',
            },
        ),
    ]
